name: Build and Check APK

on:
  push:
    branches: [ main, master ]  # Dispara ao fazer push nessas branches
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build APK (Debug)
        run: ./gradlew assembleDebug
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}  # 👈 Usa a chave secreta
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Se tiver
